export const AllBooksData = [
  {
    id: 1,
    title: "Atomic Habits",
    image: require("../assets/imge-4.jpg"),
    offer: "20% OFF",
    icons: ["book-outline", "headset-sharp"],
  },
  {
    id: 2,
    title: "Rich Dad Poor Dad",
     image: require("../assets/images-10.jpg"),
    offer: "10% OFF",
    icons: ["book-outline"],
  },
  {
    id: 3,
    title: "Think and Grow Rich",
     image: require("../assets/imge-11.jpg"),
    offer: "25% OFF",
    icons: ["headset-sharp"],
  },
  {
    id: 4,
    title: "The Alchemist",
 image: require("../assets/imge-12.jpg"),
    offer: "15% OFF",
    icons: ["book-outline", "headset-sharp"],
  },
  {
    id: 5,
    title: "Zero to One",
      image: require("../assets/images-19.jpg"),
    offer: "5% OFF",
    icons: ["book-outline"],
  },
  {
    id: 6,
    title: "Deep Work",
        image: require("../assets/imge-17.jpg"),
    offer: "30% OFF",
    icons: ["book-outline"],
  },
  {
    id: 7,
    title: "Start With Why",
     image: require("../assets/imge-14.jpg"),
    offer: "12% OFF",
    icons: ["headset-sharp"],
  },
  {
    id: 8,
    title: "The Power of Now",
     image: require("../assets/imge-15.jpg"),
    offer: "18% OFF",
    icons: ["book-outline", "headset-sharp"],
  },
  {
    id: 9,
    title: "Can't Hurt Me",
    image: require("../assets/imge-16.jpg"),
    offer: "22% OFF",
    icons: ["book-outline"],
  },
  {
    id: 10,
    title: "Ikigai",
     image: require("../assets/imge-17.jpg"),
    offer: "8% OFF",
    icons: ["book-outline"],
  },
];