export const Books = [
    {
        id: 1,
        name: "Atomic Habits",
        description: "Small habits create big changes in life.",
        chapters: 20,
        pages: 320,
        releaseDate: "2018-10-16",
        releaseTime: "10:00 AM",
        icon: "create-outline",
    },
    {
        id: 2,
        name: "Rich Dad Poor Dad",
        description: "Financial mindset and wealth building basics.",
        chapters: 10,
        pages: 200,
        releaseDate: "1997-04-01",
        releaseTime: "09:30 AM",
        icon: "create-outline",
    },
    {
        id: 3,
        name: "The Alchemist",
        description: "Follow your dreams and destiny.",
        chapters: 12,
        pages: 208,
        releaseDate: "1988-05-01",
        releaseTime: "11:00 AM",
        icon: "create-outline",
    },
    {
        id: 4,
        name: "Think and Grow Rich",
        description: "Success principles and mindset building.",
        chapters: 15,
        pages: 238,
        releaseDate: "1937-01-01",
        releaseTime: "08:00 AM",
        icon: "create-outline",
    },
    {
        id: 5,
        name: "Deep Work",
        description: "Focus deeply without distraction.",
        chapters: 8,
        pages: 304,
        releaseDate: "2016-01-05",
        releaseTime: "02:00 PM",
        icon: "create-outline",
    },
    {
        id: 6,
        name: "Zero to One",
        description: "Startup and innovation guide.",
        chapters: 7,
        pages: 210,
        releaseDate: "2014-09-16",
        releaseTime: "10:30 AM",
        icon: "create-outline",
    },
    {
        id: 7,
        name: "Ikigai",
        description: "Find purpose and happiness in life.",
        chapters: 9,
        pages: 190,
        releaseDate: "2016-08-29",
        releaseTime: "09:00 AM",
        icon: "create-outline",
    },
    {
        id: 8,
        name: "The Power of Now",
        description: "Live in the present moment.",
        chapters: 10,
        pages: 236,
        releaseDate: "1997-01-01",
        releaseTime: "07:45 AM",
        icon: "create-outline",
    },
    {
        id: 9,
        name: "Can't Hurt Me",
        description: "Mental toughness and discipline.",
        chapters: 13,
        pages: 364,
        releaseDate: "2018-12-04",
        releaseTime: "06:00 PM",
        icon: "create-outline",
    },
    {
        id: 10,
        name: "Start With Why",
        description: "Leadership through purpose.",
        chapters: 11,
        pages: 256,
        releaseDate: "2009-10-06",
        releaseTime: "12:00 PM",
        icon: "create-outline",
    },
];